# Fly.io configuration for A-Spade Frontend
app = "aspade-frontend"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DEPLOY_TARGET = "flyio"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 2

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/"
    protocol = "http"
    headers = {}

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "aspade_frontend_data"
  destination = "/app/data" 